from aiogram import types

item1_1 = types.KeyboardButton("Войти в систему")
item1_2 = types.KeyboardButton('Информация')
but1 = types.KeyboardButton('Заказы')
but2 = types.KeyboardButton('Статистика')
button1 = types.KeyboardButton('Все')
button2 = types.KeyboardButton('Новые')
button3 = types.KeyboardButton('В процессе выполнения')
button4 = types.KeyboardButton('Выполненные')
button5 = types.KeyboardButton('На главную')
help1 = types.KeyboardButton('На главную')
help2 = types.KeyboardButton('Сообщить об ошибке')
help3 = types.KeyboardButton('Предложения по улучшению')
but_st3_1 = types.KeyboardButton('Добавить')
but_st3_2 = types.KeyboardButton('Изменить')
but_st3_3 = types.KeyboardButton('Удалить')
but_st3_4 = types.KeyboardButton('Отправить сообщение')
but_st3_11 = types.KeyboardButton('Компанию')
but_st3_22 = types.KeyboardButton('Пользователя')
but_sett_1 = types.KeyboardButton('Уведомления: «вкл.»')
but_sett_2 = types.KeyboardButton('Уведомления: «выкл.»')
but_continue = types.KeyboardButton('Продолжить')
but_edit = types.KeyboardButton('Изменить')
but_applications = types.KeyboardButton('Заявки')
but_applications_all = types.KeyboardButton('Все заявки')
but_applications_expectation = types.KeyboardButton('Ожидающие')
